### ISSUE TITLE
Cannot install Orange

### ISSUE THREAD

**Issue by naranjito95** [biolab/orange#53]
I am right now using Python2.7 and tried to install Orange2.7.8 but some problems occurred. Can someone figure out what is going on? Thank you!

After I did 
$ python setup.py build
$ python setup.py install

And then ran:
$ orange-canvas

It showed:

Traceback (most recent call last):
  File "/usr/local/bin/orange-canvas", line 9, in <module>
    load_entry_point('Orange==2.7.8', 'gui_scripts', 'orange-canvas')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/Orange/OrangeCanvas/main.py", line 18, in <module>
    from PyQt4.QtGui import QFont, QColor

**Comment by kernc** [comment]
This is not the whole traceback, is it?

**Comment by kernc** [comment]
You might be missing PyQt4. Confirm it's installed using your OS' package manager, e.g.
`sudo apt install python-qt4` or similar.

**Comment by naranjito95** [comment]
It works! Thank you. However, there is an `Invalid/unknown intersphinx inventory format.` , is it normal to have this thing?

**Comment by kernc** [comment]
Various non-fatal warnings might be issued, I guess.
